'use client';

import React, { useState, useEffect, useCallback } from 'react';
import {
  Box,
  Container,
  Heading,
  Text,
  Table,
  Thead,
  Tbody,
  Tr,
  Th,
  Td,
  Badge,
  Button,
  Select,
  Input,
  useToast,
  Flex,
  Spacer,
  HStack,
  Card,
  CardBody,
  CardHeader,
  Divider,
  InputGroup,
  InputLeftElement,
  IconButton,
  useDisclosure,
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalFooter,
  ModalBody,
  ModalCloseButton,
  useColorModeValue,
  VStack,
  Alert,
  AlertIcon,
  AlertTitle,
  AlertDescription,
  Stat,
  StatLabel,
  StatNumber,
  StatHelpText,
  Grid,
  GridItem
} from '@chakra-ui/react';
import { SearchIcon, EditIcon, CheckIcon, CloseIcon } from '@chakra-ui/icons';
import { useUser } from '../../context/UserContext';
import { Copy } from '../../types/copy';
import dataService from '../../services/dataService';

interface AutoGeneratedCopy extends Copy {
  isAutoGenerated: boolean;
  suggestedSlug?: string;
  spanishText?: string; // Texto en español para mostrar siempre
  affectedLanguages?: string[];
  totalTranslations?: number;
  originalSlug?: string; // Slug original para la actualización
  originalCopyIds?: string[]; // IDs originales de los copys
}

/**
 * Página de tareas para developers
 * Muestra los textos que necesitan revisión de slugs auto-generados
 */
export default function DeveloperTasks() {
  const { currentUser } = useUser();
  const toast = useToast();
  
  const [autoGeneratedCopies, setAutoGeneratedCopies] = useState<AutoGeneratedCopy[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedLanguage, setSelectedLanguage] = useState('all');
  const [searchTerm, setSearchTerm] = useState('');
  
  // Estado para manejar la edición de cada elemento individualmente
  const [editingItems, setEditingItems] = useState<Record<string, string>>({});
  
  const [stats, setStats] = useState({
    total: 0,
    byLanguage: {} as Record<string, number>
  });

  const { isOpen, onOpen, onClose } = useDisclosure();
  const [selectedCopy, setSelectedCopy] = useState<AutoGeneratedCopy | null>(null);

  const languages = [
    { code: 'all', name: 'Todos los idiomas' },
    { code: 'es', name: 'Español' },
    { code: 'en', name: 'English' },
    { code: 'fr', name: 'Français' },
    { code: 'de', name: 'Deutsch' },
    { code: 'it', name: 'Italiano' },
    { code: 'pt', name: 'Português' }
  ];

  // Función para detectar si un slug es auto-generado
  const isSlugAutoGenerated = useCallback((slug: string, text: string, metadata?: any): boolean => {
    // Si el slug ha sido revisado manualmente, ya no se considera auto-generado
    if (metadata?.manuallyReviewed) {
      return false;
    }
    
    const autoPatterns = [
      /^auto_/,
      /^text_\d+/,
      /\d{10,}/,  // timestamps
      /^[a-z]+_\d+$/,
      /^copy_\d+$/
    ];

    return autoPatterns.some(pattern => pattern.test(slug));
  }, []);

  // Función para generar sugerencia de slug basada en el texto
  const generateSuggestedSlug = useCallback((text: string): string => {
    return text
      .toLowerCase()
      .replace(/[áàäâ]/g, 'a')
      .replace(/[éèëê]/g, 'e')
      .replace(/[íìïî]/g, 'i')
      .replace(/[óòöô]/g, 'o')
      .replace(/[úùüû]/g, 'u')
      .replace(/[ñ]/g, 'n')
      .replace(/[^a-z0-9\s]/g, '')
      .trim()
      .split(/\s+/)
      .slice(0, 3)
      .join('_');
  }, []);

  /**
   * Función para cargar los copys que necesitan revisión de slug
   * Implementada con useCallback para mantenerla estable entre renderizados
   * y evitar ciclos infinitos cuando se usa como dependencia en useEffect
   */
  const fetchAutoGeneratedCopies = useCallback(async () => {
    console.log('🔄 ===== FETCHAUTOGENERATEDCOPIES - INICIO =====');
    
    try {
      // Verificar si el usuario sigue autenticado antes de hacer la petición
      if (!currentUser) {
        console.log('🔧 Developer Tasks: Usuario no autenticado, no se cargarán los datos');
        return;
      }

      setLoading(true);
      console.log('📡 Haciendo petición a /api/copys...');
      
      const response = await fetch('/api/copys?needsSlugReview=true', {
        // Añadir cabeceras para evitar problemas de caché
        headers: {
          'Cache-Control': 'no-cache',
          'Pragma': 'no-cache'
        }
      });
      
      if (!response.ok) {
        throw new Error(`Error HTTP: ${response.status}`);
      }
      
      const data = await response.json();
      
      console.log('📥 RESPUESTA DE API /api/copys:', {
        success: data.success,
        totalCopys: data.data?.length || 0,
        error: data.error
      });

      if (data.success && Array.isArray(data.data)) {
        // Agrupar copys por slug para trabajar con ellos independientemente del idioma
        const slugGroups: Record<string, Copy[]> = {};
        
        // Primero agrupamos todos los copys por slug
        data.data.forEach((copy: Copy) => {
          // Asegurarnos de que el copy tiene la propiedad needsSlugReview a true
          if (copy.needsSlugReview) {
            if (!slugGroups[copy.slug]) {
              slugGroups[copy.slug] = [];
            }
            slugGroups[copy.slug].push(copy);
          }
        });
        
        console.log(`📊 ANÁLISIS DE COPYS PARA REVISIÓN:`);
        console.log('Total copys en BD:', data.data.length);
        console.log('Necesitan revisión de slug:', Object.keys(slugGroups).length);
        
        if (Object.keys(slugGroups).length > 0) {
          // Verificar grupos de traducción
          const withGroups = data.data.filter(copy => copy.translationGroupId);
          const withoutGroups = data.data.filter(copy => !copy.translationGroupId);
          console.log('Con grupo de traducción:', withGroups.length);
          console.log('Sin grupo de traducción:', withoutGroups.length);
          
          // Mostrar algunos ejemplos
          console.log('📋 PRIMEROS 5 COPYS QUE NECESITAN REVISIÓN:', data.data.slice(0, 5).map(c => ({
            id: c.id,
            slug: c.slug,
            language: c.language,
            text: c.text.substring(0, 30) + '...',
            groupId: c.translationGroupId,
            isOriginal: c.isOriginalText
          })));
          
          // Verificar si hay grupos con múltiples traducciones
          if (withGroups.length > 0) {
            const groupsMap: Record<string, any[]> = withGroups.reduce((acc, copy) => {
              const groupId = copy.translationGroupId;
              if (groupId && !acc[groupId]) {
                acc[groupId] = [];
              }
              if (groupId) {
                acc[groupId].push({
                  id: copy.id,
                  slug: copy.slug,
                  language: copy.language
                });
              }
              return acc;
            }, {} as Record<string, any[]>);
            
            console.log('📋 GRUPOS CON MÚLTIPLES TRADUCCIONES:');
            Object.entries(groupsMap).forEach(([groupId, copies]) => {
              if (copies.length > 1) {
                console.log(`Grupo ${groupId} (${copies.length} traducciones):`, copies);
              }
            });
          }
        }
        
        // Procesamos los grupos, priorizando el texto en español como referencia
        const autoGenerated = Object.entries(slugGroups).map(([slug, copies], index) => {
          // Buscar primero la versión en español
          const spanishCopy = copies.find(c => c.language === 'es');
          // Si no hay versión en español, usar la primera disponible
          const referenceCopy = spanishCopy || copies[0];
          
          const groupData = {
            ...referenceCopy,
            // Crear un ID único para cada grupo de slug
            _id: `slug_group_${index}_${slug}`,
            isAutoGenerated: true,
            suggestedSlug: generateSuggestedSlug(referenceCopy.text),
            spanishText: spanishCopy ? spanishCopy.text : 'No disponible en español',
            affectedLanguages: copies.map(c => c.language),
            totalTranslations: copies.length,
            originalSlug: slug, // Guardamos el slug original para la actualización
            originalCopyIds: copies.map(c => c.id || c._id).filter(Boolean) // Guardamos los IDs originales (usar id o _id)
          };
          
          // Debug: log para el primer grupo
          if (index === 0) {
            console.log('🔍 PRIMER GRUPO CREADO (ejemplo):', {
              groupId: groupData._id,
              originalSlug: slug,
              copiesCount: copies.length,
              originalCopyIds: groupData.originalCopyIds,
              sampleCopyStructure: copies[0] ? {
                hasId: !!copies[0].id,
                has_id: !!copies[0]._id,
                id: copies[0].id,
                _id: copies[0]._id
              } : null
            });
          }
          
          return groupData;
        });
        
        console.log('📊 RESUMEN DE GRUPOS CREADOS:', {
          totalGroups: autoGenerated.length,
          groupsWithValidIds: autoGenerated.filter(g => g.originalCopyIds.length > 0).length,
          groupsWithoutIds: autoGenerated.filter(g => g.originalCopyIds.length === 0).length
        });
        
        setAutoGeneratedCopies(autoGenerated);
        
        // Calcular estadísticas de slugs únicos
        setStats({
          total: autoGenerated.length,
          byLanguage: {}
        });
        
        console.log(`🔧 Developer: Encontrados ${autoGenerated.length} slugs auto-generados`);
      } else {
        console.error('❌ Error: Respuesta de API inválida o sin datos');
        setAutoGeneratedCopies([]);
        setStats({ total: 0, byLanguage: {} });
        
        // Solo mostrar error si el usuario sigue autenticado
        if (currentUser) {
          toast({
            title: 'Error',
            description: 'No se pudieron cargar los datos',
            status: 'error',
            duration: 3000,
            isClosable: true,
          });
        }
      }
    } catch (error) {
      console.error('❌ Error fetching auto-generated copies:', error);
      setAutoGeneratedCopies([]);
      setStats({ total: 0, byLanguage: {} });
      
      // Solo mostrar error si el usuario sigue autenticado
      if (currentUser) {
        toast({
          title: "Error de conexión",
          description: "No se pudo conectar con el servidor",
          status: "error",
          duration: 3000,
          isClosable: true,
        });
      }
    } finally {
      setLoading(false);
      console.log('🔄 ===== FETCHAUTOGENERATEDCOPIES - FIN =====');
    }
  }, [currentUser, toast, generateSuggestedSlug]);

  // Función para actualizar el slug de un copy específico
  const handleSlugUpdate = useCallback(async (copyId: string) => {
    console.log('🔄 ===== HANDLESLUGUPDATE - INICIO =====');
    console.log('🔧 Actualizando slug para copy:', copyId);
    
    const newSlugValue = editingItems[copyId];
    
    console.log('📝 DATOS DE ENTRADA:', {
      copyId,
      newSlugValue,
      hasNewSlug: !!newSlugValue?.trim(),
      editingItemsKeys: Object.keys(editingItems)
    });
    
    if (!newSlugValue || !newSlugValue.trim()) {
      console.warn('⚠️ Slug vacío o inválido');
      toast({
        title: "Error",
        description: "El slug no puede estar vacío",
        status: "error",
        duration: 3000,
        isClosable: true,
      });
      return;
    }

    if (!currentUser) {
      console.error('❌ Usuario no autenticado');
      toast({
        title: "Error de autenticación",
        description: "Debes estar autenticado para actualizar slugs",
        status: "error",
        duration: 3000,
        isClosable: true,
      });
      return;
    }

    try {
      console.log('🔍 Buscando copy en autoGeneratedCopies...');
      
      // Encontrar el copy que se está editando
      const copyToUpdate = autoGeneratedCopies.find(copy => copy._id === copyId);
      
      if (!copyToUpdate) {
        console.error('❌ Copy no encontrado en autoGeneratedCopies:', copyId);
        console.log('📋 IDs disponibles en autoGeneratedCopies:', autoGeneratedCopies.map(c => c._id));
        toast({
          title: "Error",
          description: "Copy no encontrado",
          status: "error",
          duration: 3000,
          isClosable: true,
        });
        return;
      }
      
      console.log('📋 COPY ENCONTRADO:', {
        id: copyToUpdate.id,
        currentSlug: copyToUpdate.slug,
        newSlug: newSlugValue.trim(),
        language: copyToUpdate.language,
        groupId: copyToUpdate.translationGroupId,
        isOriginal: copyToUpdate.isOriginalText,
        needsReview: copyToUpdate.needsSlugReview,
        originalCopyIds: copyToUpdate.originalCopyIds
      });

      // Usar el primer ID real del copy en lugar del ID de agrupación
      const realCopyId = copyToUpdate.originalCopyIds?.[0];
      
      console.log('🔍 VALIDANDO IDs REALES:', {
        originalCopyIds: copyToUpdate.originalCopyIds,
        firstId: realCopyId,
        idsLength: copyToUpdate.originalCopyIds?.length || 0,
        allIds: copyToUpdate.originalCopyIds
      });
      
      if (!realCopyId) {
        console.error('❌ No se encontró ID real del copy');
        console.error('📋 Estructura del copy:', copyToUpdate);
        toast({
          title: "Error",
          description: "No se encontró el ID real del copy. Revisa la consola para más detalles.",
          status: "error",
          duration: 5000,
          isClosable: true,
        });
        return;
      }

      console.log('📡 Haciendo petición PATCH a API...');
      console.log('🔗 Usando ID real del copy:', realCopyId);
      
      // Hacer la petición de actualización
      const response = await fetch(`/api/copys/${realCopyId}`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          slug: newSlugValue.trim(),
          needsSlugReview: false, // Marcar como revisado
          reviewedBy: currentUser.email,
          reviewedAt: new Date().toISOString(),
          updateAllLanguages: true // Actualizar todas las traducciones del mismo grupo
        }),
      });

      const result = await response.json();
      
      console.log('📥 RESPUESTA DE API PATCH:', {
        status: response.status,
        success: result.success,
        message: result.message,
        updatedCopiesCount: result.updatedCopies?.length || 0,
        groupId: result.groupId,
        error: result.error
      });

      if (result.success) {
        console.log('✅ Slug actualizado exitosamente');
        
        if (result.updatedCopies && result.updatedCopies.length > 0) {
          console.log('📋 COPYS ACTUALIZADOS:', result.updatedCopies.map(c => ({
            id: c._id || c.id,
            slug: c.slug,
            language: c.language,
            needsReview: c.needsSlugReview,
            groupId: c.translationGroupId
          })));
        }
        
        // Limpiar el estado de edición
        setEditingItems(prev => {
          const newState = { ...prev };
          delete newState[copyId];
          console.log('🧹 Estado de edición limpiado para:', copyId);
          return newState;
        });

        // Mostrar mensaje de éxito
        toast({
          title: "Slug actualizado",
          description: result.message || `El slug ha sido actualizado en todos los idiomas`,
          status: "success",
          duration: 3000,
          isClosable: true,
        });

        console.log('🔄 Refrescando lista de copys...');
        
        // Refrescar la lista para mostrar los cambios
        await fetchAutoGeneratedCopies();
        
        // Notificar a otras partes de la aplicación sobre la actualización
        console.log('📢 Notificando actualización de slug a otras vistas...');
        
        // 1. Disparar evento personalizado para notificar a otros componentes
        if (typeof window !== 'undefined') {
          // Crear un evento detallado con la información de la actualización
          const copysUpdatedEvent = new CustomEvent('copysUpdated', {
            detail: {
              action: 'slugUpdate',
              updatedCopies: result.updatedCopies,
              newSlug: newSlugValue.trim(),
              oldSlug: copyToUpdate.originalSlug,
              timestamp: new Date().toISOString()
            }
          });
          
          // Disparar el evento para que otros componentes lo capturen
          window.dispatchEvent(copysUpdatedEvent);
        }
        
        // 2. Forzar una actualización de datos utilizando el dataService
        console.log('🔄 Forzando actualización global de datos...');
        try {
          // Usar el dataService importado para forzar la actualización
          await dataService.refreshData();
          console.log('✅ Actualización global de datos completada');
        } catch (error) {
          console.error('❌ Error al forzar la actualización de datos:', error);
        }
        
        console.log('✅ Eventos de actualización enviados a todas las vistas');
        console.log('✅ Lista de copys refrescada');
      } else {
        console.error('❌ Error en actualización:', result.error);
        toast({
          title: "Error al actualizar",
          description: result.error || "No se pudo actualizar el slug",
          status: "error",
          duration: 3000,
          isClosable: true,
        });
      }
    } catch (error) {
      console.error('❌ ===== HANDLESLUGUPDATE - ERROR =====');
      console.error('Error al actualizar slug:', error);
      toast({
        title: "Error de conexión",
        description: "No se pudo conectar con el servidor",
        status: "error",
        duration: 3000,
        isClosable: true,
      });
    } finally {
      console.log('🔄 ===== HANDLESLUGUPDATE - FIN =====');
    }
  }, [autoGeneratedCopies, currentUser, editingItems, toast, fetchAutoGeneratedCopies]);

  const startEditing = useCallback((copyId: string, currentSlug: string) => {
    setEditingItems(prev => ({
      ...prev,
      [copyId]: currentSlug
    }));
  }, []);

  const cancelEditing = useCallback((copyId: string) => {
    setEditingItems(prev => {
      const newState = {...prev};
      delete newState[copyId];
      return newState;
    });
  }, []);

  const openCopyDetails = useCallback((copy: AutoGeneratedCopy) => {
    setSelectedCopy(copy);
    onOpen();
  }, [onOpen]);

  // Efecto para cargar los datos iniciales cuando se abre la página o cambia el usuario
  useEffect(() => {
    // Solo cargar datos si hay un usuario autenticado
    if (currentUser) {
      console.log('🔗 Cargando lista de copys que necesitan revisión de slug...');
      fetchAutoGeneratedCopies();
    }
  }, [currentUser, fetchAutoGeneratedCopies]);
  
  // Efecto para escuchar eventos de actualización de copys
  useEffect(() => {
    // Función para refrescar datos cuando haya cambios generales en la aplicación
    const handleCopysChange = () => {
      console.log('📢 Detectado evento copysUpdated, actualizando tareas de developer...');
      // Solo ejecutar si el usuario está autenticado para evitar pérdida de sesión
      if (currentUser) {
        fetchAutoGeneratedCopies();
      }
    };
    
    // Función para manejar específicamente la creación de nuevos copys
    const handleNewCopy = (event: CustomEvent) => {
      console.log('🎉 Detectado evento newCopyCreated, nuevo copy creado!');
      console.log('🔧 Detalles del nuevo copy:', event.detail);
      
      // Solo ejecutar si el usuario está autenticado
      if (currentUser) {
        // Refrescar la lista inmediatamente
        fetchAutoGeneratedCopies();
        
        // Mostrar notificación al usuario sobre el nuevo copy
        toast({
          title: 'Nuevo copy creado',
          description: 'Se ha detectado un nuevo copy que necesita revisión de slug',
          status: 'success',
          duration: 3000,
          isClosable: true,
        });
      }
    };
    
    // Suscribirse a ambos eventos
    window.addEventListener('copysUpdated', handleCopysChange);
    window.addEventListener('newCopyCreated', handleNewCopy as EventListener);
    
    // Limpiar los listeners cuando el componente se desmonta
    return () => {
      window.removeEventListener('copysUpdated', handleCopysChange);
      window.removeEventListener('newCopyCreated', handleNewCopy as EventListener);
    };
  }, [currentUser, toast, fetchAutoGeneratedCopies]);

  // Filtrar copys solo por búsqueda (ya no filtramos por idioma)
  const filteredCopies = autoGeneratedCopies.filter(copy => {
    const matchesSearch = searchTerm === '' || 
      copy.text.toLowerCase().includes(searchTerm.toLowerCase()) ||
      copy.slug.toLowerCase().includes(searchTerm.toLowerCase());
    
    return matchesSearch;
  });

  if (loading) {
    return (
      <Container maxW="container.xl" py={8}>
        <Box textAlign="center">
          <Text>Cargando tareas de developer...</Text>
        </Box>
      </Container>
    );
  }

  return (
    <Container maxW="container.xl" py={8}>
      {/* Header */}
      <Flex mb={8} alignItems="center" justifyContent="space-between">
        <Box>
          <Heading size="lg" mb={2}>
            🔧 Mis Tareas de Developer
          </Heading>
          <Text color="gray.600">
            Gestiona los textos que necesitan slugs más descriptivos
          </Text>
        </Box>
        {/* Botón de refrescar manteniendo la sesión */}
        <IconButton
          aria-label="Refrescar lista"
          icon={<span role="img" aria-label="refresh">🔄</span>}
          colorScheme="blue"
          onClick={() => {
            // Verificar que el usuario sigue autenticado
            if (currentUser) {
              console.log('🔄 Refrescando manualmente la lista de slugs...');
              fetchAutoGeneratedCopies();
              toast({
                title: 'Lista actualizada',
                description: 'Se han cargado los últimos copys que necesitan revisión',
                status: 'info',
                duration: 2000,
                isClosable: true,
              });
            } else {
              console.error('❌ Error: Usuario no autenticado');
              toast({
                title: 'Error',
                description: 'Debe iniciar sesión para actualizar la lista',
                status: 'error',
                duration: 2000,
                isClosable: true,
              });
            }
          }}
        />
      </Flex>

      {/* Estadísticas */}
      <Grid templateColumns="repeat(auto-fit, minmax(200px, 1fr))" gap={4} mb={6}>
        <Card>
          <CardBody>
            <Stat>
              <StatLabel>Total de slugs auto-generados</StatLabel>
              <StatNumber>{stats.total}</StatNumber>
              <StatHelpText>Requieren revisión</StatHelpText>
            </Stat>
          </CardBody>
        </Card>
      </Grid>

      {/* Recomendaciones para slugs i18n */}
      <Alert status="info" mb={6}>
        <AlertIcon />
        <Box>
          <AlertTitle>💡 Recomendaciones para slugs compatibles con i18n</AlertTitle>
          <AlertDescription>
            <VStack align="start" spacing={2} mt={2}>
              <Text>• <strong>Usa inglés:</strong> Los slugs deben estar en inglés para ser universales</Text>
              <Text>• <strong>Sé descriptivo:</strong> Usa palabras que describan el contenido (ej: "welcome_message", "error_validation")</Text>
              <Text>• <strong>Estructura jerárquica:</strong> Usa guiones bajos para agrupar (ej: "auth_login_title", "auth_login_button")</Text>
              <Text>• <strong>Evita caracteres especiales:</strong> Solo letras, números y guiones bajos</Text>
              <Text>• <strong>Mantén consistencia:</strong> Usa el mismo patrón en toda la aplicación</Text>
            </VStack>
          </AlertDescription>
        </Box>
      </Alert>

      {/* Filtros */}
      <Flex mb={4} flexWrap={["wrap", "nowrap"]}>
        <InputGroup maxW="400px" mr={4} mb={[4, 0]}>
          <InputLeftElement pointerEvents="none">
            <SearchIcon color="gray.300" />
          </InputLeftElement>
          <Input 
            placeholder="Buscar por texto o slug"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
          />
        </InputGroup>
      </Flex>

      {/* Tabla de slugs que necesitan revisión */}
      {filteredCopies.length > 0 ? (
        <Table variant="simple" mt={4}>
          <Thead>
            <Tr>
              <Th>Texto original</Th>
              <Th>Slug actual</Th>
              <Th>Sugerencia</Th>
              <Th>Idiomas</Th>
              <Th width="150px">Acciones</Th>
            </Tr>
          </Thead>
          <Tbody>
            {filteredCopies.map((copy) => (
              <Tr key={copy._id}>
                <Td maxW="250px" isTruncated>
                  <Text fontWeight="medium">
                    {copy.spanishText || copy.text}
                  </Text>
                </Td>
                <Td maxW="200px" isTruncated>
                  {editingItems[copy._id] !== undefined ? (
                    <InputGroup size="sm">
                      <Input
                        value={editingItems[copy._id]}
                        onChange={(e) => {
                          setEditingItems(prev => ({
                            ...prev,
                            [copy._id]: e.target.value
                          }));
                        }}
                        placeholder="Nuevo slug"
                      />
                    </InputGroup>
                  ) : (
                    <Text fontFamily="monospace" color="orange.500">
                      {copy.originalSlug}
                    </Text>
                  )}
                </Td>
                <Td maxW="200px" isTruncated>
                  <Text fontFamily="monospace" color="green.500">
                    {copy.suggestedSlug}
                  </Text>
                </Td>
                <Td>
                  <HStack spacing={1}>
                    {copy.affectedLanguages?.map((lang) => (
                      <Badge key={lang} colorScheme="blue" size="sm">
                        {lang}
                      </Badge>
                    ))}
                  </HStack>
                </Td>
                <Td>
                  {editingItems[copy._id] !== undefined ? (
                    <HStack spacing={2}>
                      <IconButton
                        aria-label="Guardar cambios"
                        icon={<CheckIcon />}
                        size="sm"
                        colorScheme="green"
                        onClick={() => handleSlugUpdate(copy._id)}
                      />
                      <IconButton
                        aria-label="Cancelar edición"
                        icon={<CloseIcon />}
                        size="sm"
                        colorScheme="red"
                        variant="outline"
                        onClick={() => cancelEditing(copy._id)}
                      />
                    </HStack>
                  ) : (
                    <HStack spacing={2}>
                      <Button
                        size="sm"
                        leftIcon={<EditIcon />}
                        colorScheme="blue"
                        variant="outline"
                        onClick={() => startEditing(copy._id, copy.originalSlug || '')}
                      >
                        Editar
                      </Button>
                    </HStack>
                  )}
                </Td>
              </Tr>
            ))}
          </Tbody>
        </Table>
      ) : (
        <Box textAlign="center" p={8} borderWidth="1px" borderRadius="lg">
          <Heading size="md" mb={2} color="gray.500">No hay slugs por revisar</Heading>
          <Text>Todos los slugs han sido revisados o aún no se han creado copys que requieran revisión.</Text>
        </Box>
      )}

      {/* Modal de detalles del copy */}
      <Modal isOpen={isOpen} onClose={onClose} size="xl">
        <ModalOverlay />
        <ModalContent>
          <ModalHeader>Detalles del Copy</ModalHeader>
          <ModalCloseButton />
          <ModalBody>
            {selectedCopy && (
              <Box>
                <Heading size="sm" mb={2}>Texto Original</Heading>
                <Text mb={4}>{selectedCopy.text}</Text>
                
                <Heading size="sm" mb={2}>Slug Actual</Heading>
                <Text fontFamily="monospace" mb={4}>{selectedCopy.originalSlug}</Text>
                
                <Heading size="sm" mb={2}>Slug Sugerido</Heading>
                <Text fontFamily="monospace" color="green.500" mb={4}>{selectedCopy.suggestedSlug}</Text>
                
                <Heading size="sm" mb={2}>Idiomas Afectados</Heading>
                <HStack spacing={2} mb={4}>
                  {selectedCopy.affectedLanguages?.map(lang => (
                    <Badge key={lang} colorScheme="blue">{lang}</Badge>
                  ))}
                </HStack>
                
                <Heading size="sm" mb={2}>ID Original</Heading>
                <Text fontFamily="monospace" fontSize="sm" mb={4}>{selectedCopy._id}</Text>
              </Box>
            )}
          </ModalBody>
          <ModalFooter>
            <Button variant="ghost" mr={3} onClick={onClose}>
              Cerrar
            </Button>
            {selectedCopy && (
              <Button 
                colorScheme="blue" 
                onClick={() => {
                  onClose();
                  startEditing(selectedCopy._id, selectedCopy.originalSlug || '');
                }}
              >
                Editar Slug
              </Button>
            )}
          </ModalFooter>
        </ModalContent>
      </Modal>
    </Container>
  );
}
