/**
 * Datos de prueba para el panel de developer
 * Incluye ejemplos de slugs auto-generados y textos para testing
 */

export const testAutoGeneratedCopies = [
  {
    _id: 'test1',
    slug: 'auto_1234567890',
    text: 'Bienvenido a nuestra aplicación',
    language: 'es',
    status: 'pending',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 'test2',
    slug: 'text_456789',
    text: 'Guardar cambios',
    language: 'es',
    status: 'pending',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 'test3',
    slug: 'copy_987654',
    text: 'Error de validación',
    language: 'es',
    status: 'pending',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: 'test4',
    slug: 'mensaje_1703875200000',
    text: 'Usuario no encontrado',
    language: 'es',
    status: 'pending',
    createdAt: new Date(),
    updatedAt: new Date()
  }
];

/**
 * Función para detectar si un slug es auto-generado
 * Misma lógica que en el componente principal
 */
export const isSlugAutoGenerated = (slug: string, text: string): boolean => {
  const autoPatterns = [
    /^auto_/,
    /^text_\d+/,
    /\d{10,}/,  // timestamps
    /^[a-z]+_\d+$/,
    /^copy_\d+$/
  ];

  return autoPatterns.some(pattern => pattern.test(slug));
};

/**
 * Función para generar sugerencia de slug
 * Misma lógica que en el componente principal
 */
export const generateSuggestedSlug = (text: string): string => {
  return text
    .toLowerCase()
    .replace(/[áàäâ]/g, 'a')
    .replace(/[éèëê]/g, 'e')
    .replace(/[íìïî]/g, 'i')
    .replace(/[óòöô]/g, 'o')
    .replace(/[úùüû]/g, 'u')
    .replace(/[ñ]/g, 'n')
    .replace(/[^a-z0-9\s]/g, '')
    .trim()
    .split(/\s+/)
    .slice(0, 3)
    .join('_');
};

/**
 * Casos de prueba para validar la detección de slugs auto-generados
 */
export const testCases = [
  {
    slug: 'auto_1234',
    text: 'Texto de prueba',
    expected: true,
    description: 'Slug con prefijo auto_'
  },
  {
    slug: 'text_456',
    text: 'Otro texto',
    expected: true,
    description: 'Slug con prefijo text_ y número'
  },
  {
    slug: 'mensaje_1703875200000',
    text: 'Mensaje con timestamp',
    expected: true,
    description: 'Slug con timestamp'
  },
  {
    slug: 'button.save',
    text: 'Guardar',
    expected: false,
    description: 'Slug descriptivo válido'
  },
  {
    slug: 'error.validation',
    text: 'Error de validación',
    expected: false,
    description: 'Slug con namespace válido'
  },
  {
    slug: 'welcome_message',
    text: 'Mensaje de bienvenida',
    expected: false,
    description: 'Slug descriptivo sin números'
  }
];

/**
 * Sugerencias esperadas para los casos de prueba
 */
export const expectedSuggestions = [
  {
    text: 'Bienvenido a nuestra aplicación',
    expected: 'bienvenido_a_nuestra'
  },
  {
    text: 'Guardar cambios',
    expected: 'guardar_cambios'
  },
  {
    text: 'Error de validación',
    expected: 'error_de_validacion'
  },
  {
    text: 'Usuario no encontrado',
    expected: 'usuario_no_encontrado'
  }
];
